version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:latest
    expose:
      - "80"
    ports:
      - "8080:80"
    environment:
      - PORT=${PORT}
      - PREFIX_PATH=${PREFIX_PATH}
      - NODE_ENV=${NODE_ENV}
      - TARGET_URL=${TARGET_URL}
